=== LN4259ZEBRA/Testing/COR_2515/Installer/ZebraInstaller/data/Installer.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="InstallTree">
      <xs:complexType mixed="true">
         <xs:sequence>
            <xs:element maxOccurs="unbounded" name="Feature">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element minOccurs="0" maxOccurs="unbounded" name="Feature">
                        <xs:complexType mixed="true">
                           <xs:sequence minOccurs="0">
                              <xs:element minOccurs="0" maxOccurs="unbounded" name="Feature">
                                 <xs:complexType mixed="true">
                                    <xs:sequence>
                                       <xs:element minOccurs="0" maxOccurs="unbounded" name="Feature">
                                          <xs:complexType>
                                             <xs:sequence>
                                                <xs:element maxOccurs="unbounded" name="Component">
                                                   <xs:complexType>
                                                      <xs:sequence>
                                                         <xs:element name="File">
                                                            <xs:complexType>
                                                               <xs:attribute name="Source" type="xs:string" use="required" />
                                                            </xs:complexType>
                                                         </xs:element>
                                                      </xs:sequence>
                                                      <xs:attribute name="Name" type="xs:string" use="required" />
                                                      <xs:attribute name="Destination" type="xs:string" use="required" />
                                                   </xs:complexType>
                                                </xs:element>
                                             </xs:sequence>
                                             <xs:attribute name="Name" type="xs:string" use="required" />
                                          </xs:complexType>
                                       </xs:element>
                                       <xs:element minOccurs="0" maxOccurs="unbounded" name="Component">
                                          <xs:complexType mixed="true">
                                             <xs:sequence>
                                                <xs:element maxOccurs="unbounded" name="File">
                                                   <xs:complexType>
                                                      <xs:attribute name="Source" type="xs:string" use="required" />
                                                   </xs:complexType>
                                                </xs:element>
                                             </xs:sequence>
                                             <xs:attribute name="Name" type="xs:string" use="required" />
                                             <xs:attribute name="Destination" type="xs:string" use="optional" />
                                          </xs:complexType>
                                       </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Name" type="xs:string" use="required" />
                                    <xs:attribute name="Destination" type="xs:string" use="optional" />
                                 </xs:complexType>
                              </xs:element>
                              <xs:element minOccurs="0" maxOccurs="unbounded" name="Component">
                                 <xs:complexType mixed="true">
                                    <xs:sequence>
                                       <xs:element maxOccurs="unbounded" name="File">
                                          <xs:complexType>
                                             <xs:attribute name="Source" type="xs:string" use="required" />
                                          </xs:complexType>
                                       </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="Name" type="xs:string" use="required" />
                                    <xs:attribute name="Destination" type="xs:string" use="required" />
                                 </xs:complexType>
                              </xs:element>
                           </xs:sequence>
                           <xs:attribute name="Name" type="xs:string" use="required" />
                        </xs:complexType>
                     </xs:element>
                     <xs:element minOccurs="0" maxOccurs="unbounded" name="Component">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element maxOccurs="unbounded" name="File">
                                 <xs:complexType>
                                    <xs:attribute name="Source" type="xs:string" use="required" />
                                 </xs:complexType>
                              </xs:element>
                           </xs:sequence>
                           <xs:attribute name="Name" type="xs:string" use="required" />
                           <xs:attribute name="Destination" type="xs:string" use="required" />
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string" use="required" />
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== LN4259ZEBRA/Testing/COR_2515/Installer/ZebraInstaller/data/test.xml
<InstallTree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Installer.xsd">
      
   <Feature Name="Test">
      <!--                  SUCCESS CASE                 -->
      <!--Many files cases-->
      <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
      <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
      <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
      
      <!--Many components case with one element-->
      <Component Name="MilDEV_contexts" Destination="[INSTALLDIR]Contexts">
         <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
      </Component>
      <Component Name="MilDEV_contexts" Destination="[INSTALLDIR]Contexts">
         <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
      </Component>
      <Component Name="MilDEV_contexts" Destination="[INSTALLDIR]Contexts">
         <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
      </Component>

      <!--Feature within feature with one component-->
      <Feature Name="Test2">
         <Component Name="MilDEV_contexts" Destination="[INSTALLDIR]Contexts">
            <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
         </Component>
      </Feature>
      
      <!--                  FAIL CASE                 -->
      <!--Cluster of feature and many components within second layer of featurecomponent -->
      <Feature Name="Test3">
         <Feature Name="Test4">
         </Feature>
         <Feature Name="Test5">
         </Feature>
         <Feature Name="Test6">
         </Feature>
         <Component Name="MilDEV_contexts" Destination="[INSTALLDIR]Contexts">
            <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
         </Component>
         <Component Name="MilDEV_contexts" Destination="[INSTALLDIR]Contexts">
            <File Source="[PATH_TO_CDBUILDER_FILES]contexts" />
         </Component>
      </Feature>    
      
   </Feature>

</InstallTree>
